Update sonar-test.yml

diff --git a/.github/workflows/sonar-test.yml b/.github/workflows/sonar-test.yml
--- a/.github/workflows/sonar-test.yml
+++ b/.github/workflows/sonar-test.yml
@@ -43,3 +43,19 @@ jobs:
         run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Check for SonarQube Issues
+        run: |
+          sonarqube_url="https://sonarcloud.io/"
+          organization_key="jayseth"
+          project_key="Github-Test-Org"
+          sonarqube_token="${{ secrets.SONARQUBE_TOKEN }}"
+        
+          report=$(curl -s -u "${sonarqube_token}:" "${sonarqube_url}/api/qualitygates/project_status?projectKey=${organization_key}:${project_key}")
+        
+          if echo "$report" | jq -e .projectStatus.status | grep -q "ERROR"; then
+            echo "SonarQube analysis failed. Vulnerabilities found."
+            exit 1
+          else
+            echo "SonarQube analysis passed. No vulnerabilities found."
+          fi
